package lt.vu.mif.usecases.mybatis.model;

public class StudentSubject {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.STUDENT_SUBJECT.STUDENTS_ID
     *
     * @mbg.generated Tue Apr 02 01:47:51 EEST 2019
     */
    private Integer studentsId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.STUDENT_SUBJECT.SUBJECTS_ID
     *
     * @mbg.generated Tue Apr 02 01:47:51 EEST 2019
     */
    private Integer subjectsId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.STUDENT_SUBJECT.STUDENTS_ID
     *
     * @return the value of PUBLIC.STUDENT_SUBJECT.STUDENTS_ID
     *
     * @mbg.generated Tue Apr 02 01:47:51 EEST 2019
     */
    public Integer getStudentsId() {
        return studentsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.STUDENT_SUBJECT.STUDENTS_ID
     *
     * @param studentsId the value for PUBLIC.STUDENT_SUBJECT.STUDENTS_ID
     *
     * @mbg.generated Tue Apr 02 01:47:51 EEST 2019
     */
    public void setStudentsId(Integer studentsId) {
        this.studentsId = studentsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.STUDENT_SUBJECT.SUBJECTS_ID
     *
     * @return the value of PUBLIC.STUDENT_SUBJECT.SUBJECTS_ID
     *
     * @mbg.generated Tue Apr 02 01:47:51 EEST 2019
     */
    public Integer getSubjectsId() {
        return subjectsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.STUDENT_SUBJECT.SUBJECTS_ID
     *
     * @param subjectsId the value for PUBLIC.STUDENT_SUBJECT.SUBJECTS_ID
     *
     * @mbg.generated Tue Apr 02 01:47:51 EEST 2019
     */
    public void setSubjectsId(Integer subjectsId) {
        this.subjectsId = subjectsId;
    }
}