package lt.vu.mif.usecases.mybatis.model;

import java.util.List;

public class Student {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.STUDENT.ID
     *
     * @mbg.generated Tue Apr 02 01:47:51 EEST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.STUDENT.FIRSTNAME
     *
     * @mbg.generated Tue Apr 02 01:47:51 EEST 2019
     */
    private String firstname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.STUDENT.LASTNAME
     *
     * @mbg.generated Tue Apr 02 01:47:51 EEST 2019
     */
    private String lastname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.STUDENT.UNIVERSITY_ID
     *
     * @mbg.generated Tue Apr 02 01:47:51 EEST 2019
     */
    private Integer universityId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.STUDENT.STUDENTNO
     *
     * @mbg.generated Tue Apr 02 01:47:51 EEST 2019
     */
    private String studentno;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.STUDENT.OPT_LOCK_VERSION
     *
     * @mbg.generated Tue Apr 02 01:47:51 EEST 2019
     */
    private Integer optLockVersion;

    private University university;

    private List<Subject> subjects;

    public University getUniversity() {
        return university;
    }

    public void setUniversity(University university) {
        this.university = university;
    }

    public List<Subject> getSubjects() {
        return subjects;
    }

    public void setSubjects(List<Subject> subjects) {
        this.subjects = subjects;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.STUDENT.ID
     *
     * @return the value of PUBLIC.STUDENT.ID
     *
     * @mbg.generated Tue Apr 02 01:47:51 EEST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.STUDENT.ID
     *
     * @param id the value for PUBLIC.STUDENT.ID
     *
     * @mbg.generated Tue Apr 02 01:47:51 EEST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.STUDENT.FIRSTNAME
     *
     * @return the value of PUBLIC.STUDENT.FIRSTNAME
     *
     * @mbg.generated Tue Apr 02 01:47:51 EEST 2019
     */
    public String getFirstname() {
        return firstname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.STUDENT.FIRSTNAME
     *
     * @param firstname the value for PUBLIC.STUDENT.FIRSTNAME
     *
     * @mbg.generated Tue Apr 02 01:47:51 EEST 2019
     */
    public void setFirstname(String firstname) {
        this.firstname = firstname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.STUDENT.LASTNAME
     *
     * @return the value of PUBLIC.STUDENT.LASTNAME
     *
     * @mbg.generated Tue Apr 02 01:47:51 EEST 2019
     */
    public String getLastname() {
        return lastname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.STUDENT.LASTNAME
     *
     * @param lastname the value for PUBLIC.STUDENT.LASTNAME
     *
     * @mbg.generated Tue Apr 02 01:47:51 EEST 2019
     */
    public void setLastname(String lastname) {
        this.lastname = lastname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.STUDENT.UNIVERSITY_ID
     *
     * @return the value of PUBLIC.STUDENT.UNIVERSITY_ID
     *
     * @mbg.generated Tue Apr 02 01:47:51 EEST 2019
     */
    public Integer getUniversityId() {
        return universityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.STUDENT.UNIVERSITY_ID
     *
     * @param universityId the value for PUBLIC.STUDENT.UNIVERSITY_ID
     *
     * @mbg.generated Tue Apr 02 01:47:51 EEST 2019
     */
    public void setUniversityId(Integer universityId) {
        this.universityId = universityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.STUDENT.STUDENTNO
     *
     * @return the value of PUBLIC.STUDENT.STUDENTNO
     *
     * @mbg.generated Tue Apr 02 01:47:51 EEST 2019
     */
    public String getStudentno() {
        return studentno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.STUDENT.STUDENTNO
     *
     * @param studentno the value for PUBLIC.STUDENT.STUDENTNO
     *
     * @mbg.generated Tue Apr 02 01:47:51 EEST 2019
     */
    public void setStudentno(String studentno) {
        this.studentno = studentno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.STUDENT.OPT_LOCK_VERSION
     *
     * @return the value of PUBLIC.STUDENT.OPT_LOCK_VERSION
     *
     * @mbg.generated Tue Apr 02 01:47:51 EEST 2019
     */
    public Integer getOptLockVersion() {
        return optLockVersion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.STUDENT.OPT_LOCK_VERSION
     *
     * @param optLockVersion the value for PUBLIC.STUDENT.OPT_LOCK_VERSION
     *
     * @mbg.generated Tue Apr 02 01:47:51 EEST 2019
     */
    public void setOptLockVersion(Integer optLockVersion) {
        this.optLockVersion = optLockVersion;
    }
}