package lt.vu.mif.usecases.mybatis.model;

public class Subject {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.SUBJECT.ID
     *
     * @mbg.generated Tue Apr 02 01:47:51 EEST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.SUBJECT.CODE
     *
     * @mbg.generated Tue Apr 02 01:47:51 EEST 2019
     */
    private String code;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.SUBJECT.NAME
     *
     * @mbg.generated Tue Apr 02 01:47:51 EEST 2019
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.SUBJECT.LECTURER
     *
     * @mbg.generated Tue Apr 02 01:47:51 EEST 2019
     */
    private String lecturer;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.SUBJECT.OPT_LOCK_VERSION
     *
     * @mbg.generated Tue Apr 02 01:47:51 EEST 2019
     */
    private Integer optLockVersion;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.SUBJECT.ID
     *
     * @return the value of PUBLIC.SUBJECT.ID
     *
     * @mbg.generated Tue Apr 02 01:47:51 EEST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.SUBJECT.ID
     *
     * @param id the value for PUBLIC.SUBJECT.ID
     *
     * @mbg.generated Tue Apr 02 01:47:51 EEST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.SUBJECT.CODE
     *
     * @return the value of PUBLIC.SUBJECT.CODE
     *
     * @mbg.generated Tue Apr 02 01:47:51 EEST 2019
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.SUBJECT.CODE
     *
     * @param code the value for PUBLIC.SUBJECT.CODE
     *
     * @mbg.generated Tue Apr 02 01:47:51 EEST 2019
     */
    public void setCode(String code) {
        this.code = code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.SUBJECT.NAME
     *
     * @return the value of PUBLIC.SUBJECT.NAME
     *
     * @mbg.generated Tue Apr 02 01:47:51 EEST 2019
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.SUBJECT.NAME
     *
     * @param name the value for PUBLIC.SUBJECT.NAME
     *
     * @mbg.generated Tue Apr 02 01:47:51 EEST 2019
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.SUBJECT.LECTURER
     *
     * @return the value of PUBLIC.SUBJECT.LECTURER
     *
     * @mbg.generated Tue Apr 02 01:47:51 EEST 2019
     */
    public String getLecturer() {
        return lecturer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.SUBJECT.LECTURER
     *
     * @param lecturer the value for PUBLIC.SUBJECT.LECTURER
     *
     * @mbg.generated Tue Apr 02 01:47:51 EEST 2019
     */
    public void setLecturer(String lecturer) {
        this.lecturer = lecturer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.SUBJECT.OPT_LOCK_VERSION
     *
     * @return the value of PUBLIC.SUBJECT.OPT_LOCK_VERSION
     *
     * @mbg.generated Tue Apr 02 01:47:51 EEST 2019
     */
    public Integer getOptLockVersion() {
        return optLockVersion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.SUBJECT.OPT_LOCK_VERSION
     *
     * @param optLockVersion the value for PUBLIC.SUBJECT.OPT_LOCK_VERSION
     *
     * @mbg.generated Tue Apr 02 01:47:51 EEST 2019
     */
    public void setOptLockVersion(Integer optLockVersion) {
        this.optLockVersion = optLockVersion;
    }
}